### ISSUE TITLE
Deploy to Heroku succeeds but site does not load properly, please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/web-jam-back#132]
Unhandled rejection Error: Error invoking t. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: Oe.b.createElement is not a function
Inner Error Stack:
TypeError: Oe.b.createElement is not a function
    at e (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:291103)
    at new t (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:291199)
    at Object.invoke (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:104216)
    at e.invoke (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:104132)
    at e.invoke (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:107561)
    at e.get (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:101757)
    at e.get (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:106744)
    at Object.invoke (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:104764)
    at e.invoke (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:104132)
    at e.invoke (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:107561)
    at e.get (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:101757)
    at e.get (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:106744)
    at t.initialize (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:380109)
    at e.initialize (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:438441)
    at t.initialize (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:437436)
    at https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:442416
    at s (https://web-jam-back-dev.herokuapp.com/common.ae4a12cd5a5667eee566.bundle.js:25:72732)
    at o._settlePromiseFromHandler (https://web-jam-back-dev.herokuapp.com/common.ae4a12cd5a5667eee566.bundle.js:25:46138)
    at o._settlePromise (https://web-jam-back-dev.herokuapp.com/common.ae4a12cd5a5667eee566.bundle.js:25:46938)
    at o._settlePromise0 (https://web-jam-back-dev.herokuapp.com/common.ae4a12cd5a5667eee566.bundle.js:25:47637)
    at o._settlePromises (https://web-jam-back-dev.herokuapp.com/common.ae4a12cd5a5667eee566.bundle.js:25:48964)
    at o._fulfill (https://web-jam-back-dev.herokuapp.com/common.ae4a12cd5a5667eee566.bundle.js:25:48007)
End Inner Error Stack
------------------------------------------------

    at e (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:291103)
    at new t (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:291199)
    at Object.invoke (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:104216)
    at e.invoke (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:104132)
    at e.invoke (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:107561)
    at e.get (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:101757)
    at e.get (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:106744)
    at Object.invoke (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:104764)
    at e.invoke (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:104132)
    at e.invoke (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:107561)
    at e.get (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:101757)
    at e.get (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:106744)
    at t.initialize (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:380109)
    at e.initialize (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:438441)
    at t.initialize (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:437436)
    at https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:442416
    at s (https://web-jam-back-dev.herokuapp.com/common.ae4a12cd5a5667eee566.bundle.js:25:72732)
    at o._settlePromiseFromHandler (https://web-jam-back-dev.herokuapp.com/common.ae4a12cd5a5667eee566.bundle.js:25:46138)
    at o._settlePromise (https://web-jam-back-dev.herokuapp.com/common.ae4a12cd5a5667eee566.bundle.js:25:46938)
    at o._settlePromise0 (https://web-jam-back-dev.herokuapp.com/common.ae4a12cd5a5667eee566.bundle.js:25:47637)
    at o._settlePromises (https://web-jam-back-dev.herokuapp.com/common.ae4a12cd5a5667eee566.bundle.js:25:48964)
    at o._fulfill (https://web-jam-back-dev.herokuapp.com/common.ae4a12cd5a5667eee566.bundle.js:25:48007)
    at new i (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:135907)
    at e.invoke (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:107591)
    at e.get (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:101757)
    at e.get (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:106744)
    at Object.invoke (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:104764)
    at e.invoke (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:104132)
    at e.invoke (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:107561)
    at e.get (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:101757)
    at e.get (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:106744)
    at t.initialize (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:380109)
    at e.initialize (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:438441)
    at t.initialize (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:437436)
    at https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:442416
From previous event:
    at o.h [as _captureStackTrace] (https://web-jam-back-dev.herokuapp.com/common.ae4a12cd5a5667eee566.bundle.js:25:10215)
    at o._then (https://web-jam-back-dev.herokuapp.com/common.ae4a12cd5a5667eee566.bundle.js:25:41585)
    at o.then (https://web-jam-back-dev.herokuapp.com/common.ae4a12cd5a5667eee566.bundle.js:25:39941)
    at t.apply (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:618648)
    at t.start (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:25:613498)
    at HTMLDocument.<anonymous> (https://web-jam-back-dev.herokuapp.com/app.18d86f24b66e957c6bf6.bundle.js:27:122844)
    at https://web-jam-back-dev.herokuapp.com/webcomponents.min.js:14:20073

**Comment by JoshuaVSherman** [comment]
aurelia/validation#445 (comment)
